# Generated by Django 2.1 on 2018-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('biosample_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
