# Generated by Django 2.2.10 on 2020-04-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200316_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species2CommonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Species to common name',
            },
        ),
        migrations.CreateModel(
            name='DADISLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplied_breed', models.CharField(max_length=255)),
                ('efabis_breed_country', models.CharField(max_length=255)),
                ('dadis_url', models.URLField(max_length=255)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Species2CommonName')),
            ],
            options={
                'unique_together': {('species', 'supplied_breed', 'efabis_breed_country')},
            },
        ),
    ]
