# Generated by Django 2.2.10 on 2020-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_fill_species2commonname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-data_source_id']},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'ordering': ['-data_source_id']},
        ),
        migrations.AlterField(
            model_name='dadislink',
            name='dadis_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
