# Generated by Django 2.2.10 on 2020-04-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200423_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalinfo',
            name='dadis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisms', to='backend.DADISLink'),
        ),
    ]
