# Generated by Django 2.2.10 on 2020-04-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_animalinfo_dadis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadislink',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='species2commonname',
            options={'ordering': ['-id'], 'verbose_name': 'Species to common name'},
        ),
        migrations.AlterField(
            model_name='animalinfo',
            name='dadis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisms', to='backend.DADISLink'),
        ),
    ]
