# Generated by Django 2.2.10 on 2020-05-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200427_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfo',
            name='species',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='animalinfo',
            index=models.Index(fields=['supplied_breed', 'efabis_breed_country'], name='backend_ani_supplie_cda5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='animalinfo',
            index=models.Index(fields=['efabis_breed_country'], name='backend_ani_efabis__0136d8_idx'),
        ),
    ]
