# Generated by Django 2.2.10 on 2020-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200507_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledatainfo',
            name='organism_part_ontology',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
