# Generated by Django 2.2.13 on 2020-07-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200508_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bisulfitesequencinginfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='chipseqhistonemodificationinfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='chipseqinfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='dnasehypersensitivityseqinfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='experimentinfo',
            name='data_source_id',
        ),
        migrations.RemoveField(
            model_name='genotypinginfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='hicinfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='rnaseqinfo',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='wholegenomesequencinginfo',
            name='sample',
        ),
        migrations.DeleteModel(
            name='AtacSeqInfo',
        ),
        migrations.DeleteModel(
            name='BisulfiteSequencingInfo',
        ),
        migrations.DeleteModel(
            name='ChipSeqHistoneModificationInfo',
        ),
        migrations.DeleteModel(
            name='ChipSeqInfo',
        ),
        migrations.DeleteModel(
            name='DnaseHypersensitivitySeqInfo',
        ),
        migrations.DeleteModel(
            name='ExperimentInfo',
        ),
        migrations.DeleteModel(
            name='GenotypingInfo',
        ),
        migrations.DeleteModel(
            name='HiCInfo',
        ),
        migrations.DeleteModel(
            name='RnaSeqInfo',
        ),
        migrations.DeleteModel(
            name='WholeGenomeSequencingInfo',
        ),
    ]
