# Generated by Django 2.2.13 on 2020-07-07 14:59

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200706_1320'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('SELECT row_number() over () AS id,\n               t1.* FROM (\n                   SELECT data_source_id,\n                          etag\n                     FROM backend_organism UNION\n                   SELECT data_source_id,\n                          etag\n                     FROM backend_specimen) AS t1', 'backend_etag'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'backend_etag'),
            atomic=False,
        ),
    ]
