# Generated by Django 2.2.16 on 2020-10-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200713_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadislink',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Is a custom DAD-IS link or is derived automatically from DAD-IS?'),
        ),
    ]
