# Generated by Django 2.2.16 on 2020-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_dadislink_is_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadislink',
            old_name='efabis_breed_country',
            new_name='country',
        ),
        migrations.AddField(
            model_name='dadislink',
            name='most_common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadislink',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadislink',
            name='transboundary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dadislink',
            unique_together={('species', 'supplied_breed', 'country')},
        ),
    ]
