# Generated by Django 2.2.16 on 2020-10-16 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201015_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadislink',
            name='other_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
