# Generated by Django 2.2.16 on 2021-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20201016_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadislink',
            name='iso3',
            field=models.CharField(default='XXX', max_length=3),
            preserve_default=False,
        ),
    ]
