# Generated by Django 2.2.20 on 2021-04-23 10:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_dadislink_iso3'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='external_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='specimen',
            name='external_references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
